language: node_js

node_js:
  - "12"

jobs:
  include:
    - stage: build
      name: Build
      if: branch = master
      services:
        - docker
      script:
        - npm run build:platforms && npm run build:web-app
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_IMAGE_NAME -f Dockerfile .
        - docker push $DOCKER_IMAGE_NAME

